import { Professional } from '../entities/professional.entity';
import { ProfessionalType } from '../common/enums';

export const professionalSeeds: Partial<Professional>[] = [
  {
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@mindcare.com',
    phone: '+1-555-0123',
    type: ProfessionalType.PSYCHOLOGIST,
    specializations: ['anxiety', 'depression', 'workplace stress', 'cognitive behavioral therapy'],
    location: 'New York, NY',
    website: 'https://drsarahjohnson.com',
    bio: 'Dr. Johnson specializes in cognitive behavioral therapy with over 10 years of experience helping professionals manage workplace stress and anxiety.',
    isAvailable: true,
    rating: 4.8,
    reviewCount: 127,
  },
  {
    name: 'Dr. Michael Chen',
    email: 'michael.chen@therapyplus.com',
    phone: '+1-555-0124',
    type: ProfessionalType.PSYCHIATRIST,
    specializations: ['depression', 'anxiety disorders', 'medication management', 'bipolar disorder'],
    location: 'San Francisco, CA',
    website: 'https://drmichaelchen.com',
    bio: 'Dr. Chen is a board-certified psychiatrist specializing in medication management and treatment of mood disorders.',
    isAvailable: true,
    rating: 4.9,
    reviewCount: 89,
  },
  {
    name: 'Lisa Rodriguez, LMFT',
    email: 'lisa.rodriguez@familytherapy.com',
    phone: '+1-555-0125',
    type: ProfessionalType.THERAPIST,
    specializations: ['relationship counseling', 'family therapy', 'communication skills', 'work-life balance'],
    location: 'Los Angeles, CA',
    website: 'https://lisarodrigueztherapy.com',
    bio: 'Lisa is a licensed marriage and family therapist who helps individuals and couples improve their relationships and achieve better work-life balance.',
    isAvailable: true,
    rating: 4.7,
    reviewCount: 156,
  },
  {
    name: 'James Wilson, LPC',
    email: 'james.wilson@counselingcenter.com',
    phone: '+1-555-0126',
    type: ProfessionalType.COUNSELOR,
    specializations: ['workplace counseling', 'stress management', 'career guidance', 'burnout prevention'],
    location: 'Chicago, IL',
    website: 'https://jameswilsoncounseling.com',
    bio: 'James specializes in workplace counseling and helps professionals navigate career challenges and prevent burnout.',
    isAvailable: true,
    rating: 4.6,
    reviewCount: 203,
  },
  {
    name: 'Dr. Emily Davis',
    email: 'emily.davis@mindwellness.com',
    phone: '+1-555-0127',
    type: ProfessionalType.PSYCHOLOGIST,
    specializations: ['trauma therapy', 'PTSD', 'mindfulness', 'stress reduction'],
    location: 'Boston, MA',
    website: 'https://dremilydavis.com',
    bio: 'Dr. Davis specializes in trauma-informed therapy and mindfulness-based interventions for stress reduction.',
    isAvailable: true,
    rating: 4.9,
    reviewCount: 94,
  },
  {
    name: 'Robert Kim, LCSW',
    email: 'robert.kim@socialwork.com',
    phone: '+1-555-0128',
    type: ProfessionalType.THERAPIST,
    specializations: ['addiction counseling', 'group therapy', 'behavioral therapy', 'crisis intervention'],
    location: 'Seattle, WA',
    website: 'https://robertkimtherapy.com',
    bio: 'Robert is a licensed clinical social worker with expertise in addiction counseling and crisis intervention.',
    isAvailable: true,
    rating: 4.5,
    reviewCount: 78,
  },
  {
    name: 'Dr. Amanda Foster',
    email: 'amanda.foster@psychiatrycare.com',
    phone: '+1-555-0129',
    type: ProfessionalType.PSYCHIATRIST,
    specializations: ['adult ADHD', 'anxiety disorders', 'mood disorders', 'psychopharmacology'],
    location: 'Austin, TX',
    website: 'https://dramandafoster.com',
    bio: 'Dr. Foster specializes in adult ADHD and anxiety disorders, with a focus on comprehensive treatment approaches.',
    isAvailable: true,
    rating: 4.8,
    reviewCount: 112,
  },
  {
    name: 'Maria Gonzalez, MA',
    email: 'maria.gonzalez@counseling.com',
    phone: '+1-555-0130',
    type: ProfessionalType.COUNSELOR,
    specializations: ['multicultural counseling', 'identity issues', 'workplace diversity', 'cultural adaptation'],
    location: 'Miami, FL',
    website: 'https://mariagonzalezcounseling.com',
    bio: 'Maria specializes in multicultural counseling and helps individuals navigate identity and cultural adaptation challenges.',
    isAvailable: true,
    rating: 4.7,
    reviewCount: 145,
  },
];